# Generated by Django 3.0.3 on 2020-02-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('semester', models.CharField(max_length=1)),
                ('academic_year', models.CharField(max_length=4)),
            ],
        ),
    ]
