# Generated by Django 3.0.3 on 2020-02-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_classroom_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Room'),
        ),
    ]
