# Generated by Django 3.0.3 on 2020-02-26 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
