# Generated by Django 3.0.3 on 2020-02-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20200226_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_code',
        ),
    ]
